 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tweeets", type: :request do
  # Tweeet. As you add validations to Tweeet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tweeet.create! valid_attributes
      get tweeets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tweeet = Tweeet.create! valid_attributes
      get tweeet_url(tweeet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tweeet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tweeet = Tweeet.create! valid_attributes
      get edit_tweeet_url(tweeet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tweeet" do
        expect {
          post tweeets_url, params: { tweeet: valid_attributes }
        }.to change(Tweeet, :count).by(1)
      end

      it "redirects to the created tweeet" do
        post tweeets_url, params: { tweeet: valid_attributes }
        expect(response).to redirect_to(tweeet_url(Tweeet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tweeet" do
        expect {
          post tweeets_url, params: { tweeet: invalid_attributes }
        }.to change(Tweeet, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tweeets_url, params: { tweeet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tweeet" do
        tweeet = Tweeet.create! valid_attributes
        patch tweeet_url(tweeet), params: { tweeet: new_attributes }
        tweeet.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tweeet" do
        tweeet = Tweeet.create! valid_attributes
        patch tweeet_url(tweeet), params: { tweeet: new_attributes }
        tweeet.reload
        expect(response).to redirect_to(tweeet_url(tweeet))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tweeet = Tweeet.create! valid_attributes
        patch tweeet_url(tweeet), params: { tweeet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tweeet" do
      tweeet = Tweeet.create! valid_attributes
      expect {
        delete tweeet_url(tweeet)
      }.to change(Tweeet, :count).by(-1)
    end

    it "redirects to the tweeets list" do
      tweeet = Tweeet.create! valid_attributes
      delete tweeet_url(tweeet)
      expect(response).to redirect_to(tweeets_url)
    end
  end
end
